config/routes.rb
Evernote::Application.routes.draw do
  root to: 'static_pages#root'
  resources :users
  resource :session

  namespace :api, defaults: { format: :json } do
    resources :notebooks, except: [:new, :edit]
    resources :notes, only: [:create, :show, :update, :destroy]
    resources :tags, only: [:index, :show]
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :title, :notebook_id, presence: true

  belongs_to :notebook
  has_many :taggings
  has_many :tags, through: :taggings

  default_scope { order('created_at DESC')}
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user
  has_many :notes

  def is_member?(user)
    user.id == self.user_id
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :notes, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :note
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true

  has_many :notebooks
  has_many :notes, through: :notebooks
  has_many :taggings, through: :notes
  has_many :tags, through: :taggings

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    before_action :require_signed_in!

    def require_notebook_member!
      # redirect_to new_session_url unless current_board.is_member?(current_user)
    end
  end
end

app/controllers/api/notebooks_controller.rb
module Api
  class NotebooksController < ApiController
    def create
      @notebook = current_user.notebooks.new(notebook_params)

      if @notebook.save
        render json: @notebook
      else
        render json: @notebook.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @notebook = current_user.notebooks.find(params[:id])
      @notebook.try(:destroy)
      render json: {}
    end

    def index
      @notebooks = current_user.notebooks
      render json: @notebooks
    end

    def show
      @notebook = current_user.notebooks.find(params[:id])

      if @notebook.is_member?(current_user)
        render :show
      else
        render json: ["You don't have permission to see this"], status: 403
      end
    end

    private

    def notebook_params
      params.require(:notebook).permit(:title)
    end
  end
end

app/controllers/api/notes_controller.rb
module Api
  class NotesController < ApiController
    # before_action #require_notebook_member!

    def create
      @note = current_notebook.notes.new(note_params)

      if @note.save
        render json: @note
      else
        render json: @note.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @note = Note.find(params[:id])
      @note.destroy()
      render json: {}
    end

    def update
      @note = Note.find(params[:id])
      if @note.update(note_params)
        render json: @note
      else
        render json: @note.erorrs.full_messages, status: :unprocessable_entity
      end
    end

    def show
      @note = Note.find(params[:id])
      render :show
    end

    private

    def current_notebook
      if params[:id]
        @note = Note.find(params[:id])
        @notebook = @note.notebook
      elsif params[:note]
        @notebook = Notebook.find(params[:note][:notebook_id])
      end
    end

    def note_params
      params.require(:note).permit(:title, :body, :notebook_id)
    end

  end
end

app/controllers/api/tags_controller.rb
module Api
  class TagsController < ApiController
    def index
      @tags = current_user.tags
      render json: @tags
    end

    def show
      @tag = Tag.find(params[:id])
      render :show
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out!
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])

    if @user
      sign_in!(@user)
      redirect_to "/#notebooks"
    else
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to "#notebooks"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end   

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forevernote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<%= error %>
	<% end %>
<% end %>

<!-- <% if current_user %>
  <%= current_user.email %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %> -->


<%= yield %>

</body>
</html>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <nav class="navbar navbar-default navbar-premium-wrapper" role="navigation">
    <ul class="nav navbar-nav navbar-left">
      <li>Upgrade for free!</li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign Out", session_url, id: "sign-out", method: :delete %></li>
    </ul>
</nav>
  <div id="main" class="container-fluid">

    
    
  </div>

</div>

app/views/users/new.html.erb
<div class="container">
  <div id="bg">
    <img src="<%= asset_path 'backgroundforest.jpg' %>" alt="">
  </div>
    <div class="row">
        <div class="col-md-12">
            <div class="pr-wrap">
                <div class="pass-reset">
                    <label>
                        Enter the email you signed up with</label>
                    <input type="email" placeholder="Email" />
                    <input type="submit" value="Submit" class="pass-reset-submit btn btn-success btn-sm" />
                </div>
            </div>
            <div class="wrap">
                <p class="form-title">
                    Sign Up</p>
                <form action="<%= users_url %>" method="POST" class="login">
                      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="text" placeholder="Username" name="user[email]" />
                <input type="password" placeholder="Password" name="user[password]" />
                <input type="submit" value="Sign Up" class="btn btn-success btn-sm" />
                <button class="btn btn-success btn-sm"><%= link_to "Already have an account?", new_session_url %></button>
                </form>
            </div>
        </div>
    </div>
</div>